name: Deploy to GitHub Pages

on:
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Check GitHub Pages Status
        run: |
          echo "::notice::Verifying GitHub Pages configuration..."
          echo "If deployment fails with 404, ensure GitHub Pages is enabled at:"
          echo "https://github.com/${{ github.repository }}/settings/pages"
          echo "Set the source to 'GitHub Actions' in the repository settings."
      
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Build with Next.js
        run: npm run build
      
      - name: Export Next.js to static (create ./out)
        run: |
          # Use npm run export if present, otherwise fall back to npx next export
          npm run export --if-present || npx next export -o out

      - name: Configure GitHub Pages
        uses: actions/configure-pages@v3

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./out

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
